security:
    firewalls:
        main:
            anonymous: ~
            provider: database_users
            guard:
                authenticators:
                    - login_authenticator
    encoders:
            PiupiuBundle\Entity\User:
              algorithm: bcrypt
              cost: 13
    providers:
        database_users:
            entity:
              class: PiupiuBundle:User
              property: username